# Generated by Django 2.2.4 on 2019-11-01 12:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Untitled Plan', max_length=32)),
                ('price', models.DecimalField(decimal_places=2, default=None, max_digits=6, null=True)),
                ('subscription_period', models.DurationField(default=datetime.timedelta(31))),
                ('type', models.CharField(choices=[('premium', 'Premium'), ('basic', 'Basic')], default='basic', max_length=32)),
            ],
        ),
    ]
