# Generated by Django 2.2.4 on 2019-11-13 15:35

from django.conf import settings
from django.db import migrations, models
import payments.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Checkout',
            fields=[
                ('checkout_id', models.CharField(default=uuid.uuid4, editable=False, max_length=40, primary_key=True, serialize=False, unique=True)),
                ('stripe_id', models.CharField(blank=True, editable=False, max_length=100, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('is_paid', models.BooleanField(blank=True, default=False, editable=False)),
                ('is_cancelled', models.BooleanField(blank=True, default=False, editable=False)),
                ('payment_plan', models.ForeignKey(editable=False, on_delete=models.SET(payments.models.get_sentinel_user), to='payments.Plan')),
                ('user', models.ForeignKey(editable=False, on_delete=models.SET(payments.models.get_sentinel_user), to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
