# Generated by Django 2.2.4 on 2019-11-28 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_checkout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='type',
            field=models.CharField(choices=[('corporate', 'Corporate'), ('premium', 'Premium'), ('basic', 'Basic')], default='basic', max_length=32),
        ),
    ]
