# Generated by Django 2.2.4 on 2020-01-21 15:43

from django.db import migrations

def create_sentinel_user(app, schema_editor):
    db_alias = schema_editor.connection.alias

    User = app.get_model('authentication', 'User')
    User.objects.using(db_alias).create(email='deleted@user.com')

def delete_sentinel_user(app, schema_editor):
    db_alias = schema_editor.connection.alias

    User = app.get_model('authentication', 'User')
    User.objects.using(db_alias).get(email='deleted@user.com').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '004_create_sentinel_plan'),
    ]

    operations = [
             migrations.RunPython(create_sentinel_user, delete_sentinel_user)
    ]
