# Generated by Django 2.2.4 on 2020-01-29 14:00

from django.db import migrations, models
import payments.models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_create_sentinel_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='payment_plan',
            field=models.ForeignKey(editable=False, on_delete=models.SET(payments.models.get_sentinel_plan), to='payments.Plan'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='type',
            field=models.CharField(choices=[('corporate', 'Corporate'), ('premium', 'Premium'), ('basic', 'Basic'), ('deleted', 'Deleted')], default='basic', max_length=32),
        ),
    ]
