# Generated by Django 2.2.4 on 2020-04-20 10:14

from django.db import migrations


def assing_numbers(app, schema_editor):
    db_alias = schema_editor.connection.alias

    Checkout = app.get_model('payments', 'Checkout')
    Invoice = app.get_model('payments', 'Invoice')

    for c in Checkout.objects.using(db_alias).filter(is_paid=True):
        c.invoice = Invoice.objects.using(db_alias).create()
        c.save()



class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0007_auto_20200417_1121'),
    ]

    operations = [
             migrations.RunPython(assing_numbers)
    ]
