# Generated by Django 2.2.4 on 2020-04-21 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0010_populate_country_vat_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxationcountry',
            name='exclude_vat',
            field=models.BooleanField(default=False, help_text='Check this, if companies with VAT number should have 0% VAT charge (EU only)'),
        ),
    ]
