# Generated by Django 2.2.4 on 2020-04-23 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0011_auto_20200421_0818'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='_backups',
            field=models.TextField(default=''),
        ),
    ]
