# Generated by Django 2.2.4 on 2020-05-05 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0012_backup_invoice_context'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='stripe_plan_id',
            field=models.CharField(default='', editable=False, max_length=32),
        ),
    ]
