# Generated by Django 2.2.4 on 2020-05-07 05:44

from django.db import migrations

def transfer_data_to_invoice(app, schema_editor):
    db_alias = schema_editor.connection.alias
    Checkout = app.get_model('payments', 'Checkout')

    for checkout in Checkout.objects.using(db_alias).exclude(invoice=None):
        checkout.invoice.user = checkout.user
        checkout.invoice._one_time_payment = checkout
        checkout.invoice.date_paid = checkout.created
        checkout.invoice.save()


def transfer_data_to_checkout(app, schema_editor):
    db_alias = schema_editor.connection.alias
    Invoice = app.get_model('payments', 'Invoice')

    for invoice in Invoice.objects.using(db_alias).exclude(_one_time_payment=None):
        invoice._one_time_payment.user = invoice.user
        invoice._one_time_payment.invoice = invoice
        invoice._one_time_payment.save()


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0014_auto_20200507_0842'),
    ]

    operations = [
            migrations.RunPython(transfer_data_to_invoice, transfer_data_to_checkout)
    ]
