# Generated by Django 2.2.4 on 2020-05-07 06:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0015_transfer_invoice_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkout',
            name='invoice',
        ),
        migrations.AlterField(
            model_name='invoice',
            name='_one_time_payment',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paid_invoice', to='payments.Checkout'),
        ),
    ]
