# Generated by Django 2.2.4 on 2020-05-15 06:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0019_create_basic_currencies'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='currency',
            field=models.ForeignKey(default='EUR', on_delete=django.db.models.deletion.CASCADE, to='payments.Currency'),
        ),
    ]
