# Generated by Django 2.2.4 on 2020-05-25 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0021_create_corporations_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='extra_info_text',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='plan',
            name='max_users_allowed',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
