# Generated by Django 2.2.4 on 2020-05-29 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0022_auto_20200525_1157'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='interval',
            field=models.CharField(default='', max_length=15),
        ),
    ]
