# Generated by Django 2.2.4 on 2020-06-04 08:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payments', '0023_plan_interval'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('homepage', models.URLField(max_length=350)),
                ('logo', models.TextField(editable=False)),
                ('voucher_prefix', models.CharField(max_length=20, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='RedeemedVoucher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_redeemed', models.DateTimeField(auto_now_add=True)),
                ('visible_to_user', models.BooleanField(default=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=9)),
                ('max_uses', models.PositiveIntegerField()),
                ('valid_till', models.DateField()),
                ('bonus_days', models.PositiveIntegerField()),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payments.Partner')),
                ('redeemed_by', models.ManyToManyField(editable=False, through='payments.RedeemedVoucher', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='redeemedvoucher',
            name='voucher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='payments.Voucher'),
        ),
    ]
