# Generated by Django 2.2.4 on 2020-07-20 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0024_auto_20200604_1102'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='affiliation_text',
            field=models.CharField(default='PROVIDED BY', max_length=64),
        ),
    ]
