# Generated by Django 2.2.4 on 2020-08-04 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0025_partner_affiliation_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voucher',
            name='number',
            field=models.CharField(max_length=30),
        ),
    ]
