# Generated by Django 2.2.4 on 2020-09-07 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0026_auto_20200804_1017'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='conversion_rate',
            field=models.DecimalField(decimal_places=5, default=1, max_digits=9),
        ),
    ]
