# Generated by Django 2.2.4 on 2020-09-14 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0029_auto_20200909_1909'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='banner',
            field=models.TextField(default='', editable=False),
        ),
    ]
