# Generated by Django 2.2.4 on 2020-09-17 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0031_scale_partner_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='banner_link',
            field=models.URLField(blank=True, default='', max_length=350),
        ),
    ]
