definitions:
  steps:
    - step: &test
        name: 'Run tests'
        image: 'python:3.6-slim-buster'
        script:
          # mysqlclient is not required for testing
          - sed -i -e '/mysqlclient/d' requirements.txt
          - pip install -r requirements.txt
            # update all deplyments, except test and develop
            # regex is mached from beginning of string
          - manage.py test
    - step: &compress
          name: 'Compress package'
          image: 'atlassian/default-image:2'
          script:
            - zip -r release.zip ./ -x ./.git
          artifacts: 
            - release.zip
    - step: &deploy
        name: 'Deploy package'
        image: 'python:3.7.3'
        script:
          - pip install boto3
            # update all deplyments, except test and develop
            # regex is mached from beginning of string
          - python deploy-aws.py release.zip '((?!(develop|test)).+|(develop|test).+|)$'
pipelines:
  branches:
    aws:
      - step: *compress
      - step:
          <<: *deploy
          script:
            - pip install boto3
            - python deploy-aws.py release.zip 'develop$'
    test:
      - step: *compress
      - step:
          <<: *deploy
          script:
            - pip install boto3
            - python deploy-aws.py release.zip 'test$'

    master:
      - step: *compress
      - step: *deploy
