# Generated by Django 2.2.2 on 2019-07-16 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='session',
            old_name='session_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='session',
            old_name='session_number',
            new_name='number',
        ),
    ]
