# Generated by Django 2.2.2 on 2019-07-16 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0003_auto_20190716_0806'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='machine',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='session.Machine'),
        ),
    ]
