# Generated by Django 2.2.2 on 2019-07-16 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0004_session_machine'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='material',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='session.Material'),
        ),
    ]
