# Generated by Django 2.2.2 on 2019-08-08 09:59

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0006_machine_pub_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chamber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chamber_heatable', models.BooleanField(default=False)),
                ('tool', models.CharField(blank=True, choices=[('T0', 'T0'), ('T1', 'T1'), ('T2', 'T2')], max_length=3)),
                ('gcode_command', models.CharField(default='M141 S$temp', max_length=40)),
                ('temperature_max', models.IntegerField(default=80)),
            ],
        ),
        migrations.CreateModel(
            name='Nozzle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size_id', models.DecimalField(decimal_places=1, default=0.4, max_digits=2)),
            ],
        ),
        migrations.CreateModel(
            name='Printbed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('printbed_heatable', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20)),
                ('pub_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('min_max_parameter_one_min', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('min_max_parameter_one_max', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('min_max_parameter_two_min', models.IntegerField(default=0)),
                ('min_max_parameter_two_max', models.IntegerField(default=0)),
                ('speed_travel', models.IntegerField(default=140)),
                ('raft_density', models.IntegerField(default=100)),
                ('speed_printing_raft', models.IntegerField(default=25)),
                ('track_height', models.DecimalField(decimal_places=2, default=0.2, max_digits=3)),
                ('track_height_raft', models.DecimalField(decimal_places=2, default=0.2, max_digits=3)),
                ('track_width', models.DecimalField(decimal_places=2, default=0.3, max_digits=3)),
                ('track_width_raft', models.DecimalField(decimal_places=2, default=0.3, max_digits=3)),
                ('extrusion_multiplier', models.DecimalField(decimal_places=2, default=1.0, max_digits=3)),
                ('temperature_extruder', models.IntegerField(default=260)),
                ('temperature_extruder_raft', models.IntegerField(default=260)),
                ('retraction_restart_distance', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('retraction_speed', models.IntegerField(default=100)),
                ('retraction_distance', models.DecimalField(decimal_places=2, default=2.6, max_digits=4)),
                ('bridging_extrusion_multiplier', models.DecimalField(decimal_places=1, default=1, max_digits=3)),
                ('bridging_part_cooling', models.IntegerField(default=100)),
                ('bridging_speed_printing', models.IntegerField(default=40)),
                ('speed_printing', models.IntegerField(default=80)),
                ('coasting_distance', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('critical_overhang_angle', models.IntegerField(default=53.0)),
                ('temperature_printbed_setpoint', models.IntegerField(default=90)),
                ('temperature_chamber_setpoint', models.IntegerField(default=80)),
                ('part_cooling_setpoint', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='session',
            name='test_number',
            field=models.CharField(choices=[('01', 'First-layer printing height test'), ('03', 'Extrusion temperature test'), ('10', 'Retraction distance test'), ('11', 'Bridging test')], default='01', max_length=20),
        ),
        migrations.CreateModel(
            name='Extruder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('pub_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('tool', models.CharField(blank=True, choices=[('T0', 'T0'), ('T1', 'T1'), ('T2', 'T2')], default='T0', max_length=3)),
                ('temperature_max', models.IntegerField(default=350)),
                ('part_cooling', models.BooleanField(default=True)),
                ('nozzle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='session.Nozzle')),
            ],
        ),
        migrations.AddField(
            model_name='machine',
            name='chamber',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='session.Chamber'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='machine',
            name='extruder',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='session.Extruder'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='machine',
            name='printbed',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='session.Printbed'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='session',
            name='settings',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='session.Settings'),
        ),
    ]
