# Generated by Django 2.2.4 on 2019-08-19 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0010_auto_20190808_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='target',
            field=models.CharField(choices=[('mechanical_strength', 'Mechanical Strength'), ('aesthetics', 'Aesthetics'), ('fast_printing', 'Fast Printing')], default='mechanical_strength', max_length=20),
        ),
    ]
