# Generated by Django 2.2.4 on 2019-08-20 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0012_testinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='persistence',
            field=models.TextField(default='', max_length=100000),
        ),
    ]
