# Generated by Django 2.2.4 on 2019-08-22 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0014_auto_20190821_1328'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='_min_max_parameter_one',
            field=models.CharField(default='[]', max_length=20),
        ),
        migrations.AddField(
            model_name='session',
            name='_min_max_parameter_three',
            field=models.CharField(default='[]', max_length=20),
        ),
        migrations.AddField(
            model_name='session',
            name='_min_max_parameter_two',
            field=models.CharField(default='[]', max_length=20),
        ),
    ]
