# Generated by Django 2.2.4 on 2019-08-22 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0015_auto_20190822_1507'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='settings',
            name='min_max_parameter_one_max',
        ),
        migrations.RemoveField(
            model_name='settings',
            name='min_max_parameter_one_min',
        ),
        migrations.RemoveField(
            model_name='settings',
            name='min_max_parameter_two_max',
        ),
        migrations.RemoveField(
            model_name='settings',
            name='min_max_parameter_two_min',
        ),
    ]
