# Generated by Django 2.2.4 on 2019-08-28 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0018_auto_20190825_2024'),
    ]

    operations = [
        migrations.AddField(
            model_name='printbed',
            name='temperature_max',
            field=models.IntegerField(default=120),
        ),
    ]
