# Generated by Django 2.2.4 on 2019-08-28 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0019_printbed_temperature_max'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extruder',
            name='name',
        ),
    ]
