# Generated by Django 2.2.4 on 2019-09-03 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0020_remove_extruder_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='session',
            old_name='test_number',
            new_name='_test_number',
        ),
        migrations.AddField(
            model_name='session',
            name='_printing_speed',
            field=models.CharField(default='[0,0]', max_length=20),
        ),
        migrations.AlterField(
            model_name='settings',
            name='bridging_part_cooling',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='settings',
            name='bridging_speed_printing',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='settings',
            name='critical_overhang_angle',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='settings',
            name='retraction_distance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='settings',
            name='speed_printing',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='settings',
            name='speed_printing_raft',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='settings',
            name='temperature_chamber_setpoint',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='settings',
            name='temperature_extruder',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='settings',
            name='temperature_extruder_raft',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='settings',
            name='temperature_printbed_setpoint',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='settings',
            name='track_height',
            field=models.DecimalField(decimal_places=2, default=0.15, max_digits=3),
        ),
        migrations.AlterField(
            model_name='settings',
            name='track_height_raft',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
        migrations.AlterField(
            model_name='settings',
            name='track_width',
            field=models.DecimalField(decimal_places=2, default=0.4, max_digits=3),
        ),
        migrations.AlterField(
            model_name='settings',
            name='track_width_raft',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
    ]
