# Generated by Django 2.2.4 on 2019-09-05 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0021_auto_20190903_1226'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='_test_info',
            field=models.TextField(default='', max_length=1000000),
        ),
        migrations.AlterField(
            model_name='session',
            name='_min_max_parameter_one',
            field=models.CharField(default='[]', max_length=20),
        ),
    ]
