# Generated by Django 2.2.4 on 2019-09-11 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0022_auto_20190905_1146'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='_previously_tested_parameters',
            field=models.TextField(default='', max_length=1000000),
        ),
        migrations.AlterField(
            model_name='settings',
            name='track_height',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
        migrations.AlterField(
            model_name='settings',
            name='track_width',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
    ]
