# Generated by Django 2.2.4 on 2019-10-03 09:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0025_auto_20191002_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extruder',
            name='pub_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='machine',
            name='pub_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 10, 3, 9, 39, 7, 117049, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='material',
            name='pub_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 10, 3, 9, 39, 7, 115329, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='session',
            name='pub_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='settings',
            name='pub_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='testinfo',
            name='datetime_info',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
