# Generated by Django 2.2.4 on 2019-10-14 07:51

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0026_auto_20191003_1239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='extruder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='session.Extruder'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='pub_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='material',
            name='pub_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='session',
            name='target',
            field=models.CharField(choices=[('mechanical_strength', 'Mechanical Strength'), ('aesthetics', 'Aesthetics'), ('fast_printing', 'Short printing time')], default='mechanical_strength', max_length=20),
        ),
    ]
