# Generated by Django 2.2.7 on 2019-12-06 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0029_machine_extruder_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='extruder_type',
            field=models.CharField(choices=[('bowden', 'Bowden'), ('directdrive', 'Direct drive')], default='bowden', max_length=20),
        ),
        migrations.AlterField(
            model_name='settings',
            name='retraction_speed',
            field=models.IntegerField(default=0),
        ),
    ]
