# Generated by Django 2.2.4 on 2019-12-18 18:55

from django.db import migrations, models


IGNORABLE_FIELDS = ('owner', 'settings')
def copy_recursively(instance):
    fields = (f for f in instance._meta.get_fields() if isinstance(f, models.ForeignKey) and f.name not in IGNORABLE_FIELDS)

    for field in fields:
        v = getattr(instance, field.name)
        if v is not None:
            copy_recursively(v)
            v.pk = None
            if hasattr(v, 'owner'):
                v.owner = None
            v.save()
            setattr(instance, field.name, v)




def copy_dependancies(apps, schema_editor):
    Session = apps.get_model('session', 'Session')
    # call save on each session to create copy material and machine
    for s in Session.objects.all():
        copy_recursively(s)
        s.save()


def revert_dependancies(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('session', '0030_auto_20191206_1521'),
    ]

    operations = [
            migrations.RunPython(copy_dependancies, revert_dependancies),
    ]
