# Generated by Django 2.2.4 on 2020-01-08 09:21

from django.db import migrations
from django.conf import settings
import json

MACHINE_SAMPLES = '''
    [
      {
        "model": "101Hero",
        "buildarea_maxdim1": 149.86,
        "buildarea_maxdim2": 149.86,
        "form": "elliptic",
        "extruder": {
          "nozzle": {
            "size_id": 0.4
          }
        },
        "printbed": {
          "printbed_heatable": false
        }
      },
      {
        "model": "3Dator",
        "buildarea_maxdim1": 180,
        "buildarea_maxdim2": 170,
        "form": "cartesian",
        "extruder": {
          "nozzle": {
            "size_id": 0.5
          }
        },
        "printbed": {
          "printbed_heatable": true
        }
      },
      {
        "model": "3DMaker Starter",
        "buildarea_maxdim1": 210,
        "buildarea_maxdim2": 185,
        "form": "cartesian",
        "extruder": {
          "nozzle": {
            "size_id": 0.4
          }
        },
        "printbed": {
          "printbed_heatable": false
        }
      },
      {
        "model": "Alfawise U20",
        "buildarea_maxdim1": 300,
        "buildarea_maxdim2": 300,
        "form": "cartesian",
        "extruder": {
          "nozzle": {
            "size_id": 0.4
          }
        },
        "printbed": {
          "printbed_heatable": true
        }
      },
      {
        "model": "Alfawise U30",
        "buildarea_maxdim1": 220,
        "buildarea_maxdim2": 220,
        "form": "cartesian",
        "extruder": {
          "nozzle": {
            "size_id": 0.4
          }
        },
        "printbed": {
          "printbed_heatable": true
        }
      },
      {
        "model": "ALYA 3DP",
        "buildarea_maxdim1": 100,
        "buildarea_maxdim2": 100,
        "form": "cartesian",
        "extruder": {
          "nozzle": {
            "size_id": 0.4
          }
        },
        "printbed": {
          "printbed_heatable": false
        }
      },
      {
        "model": "ALYA NX 3DP",
        "buildarea_maxdim1": 180,
        "buildarea_maxdim2": 160,
        "form": "cartesian",
        "extruder": {
          "nozzle": {
            "size_id": 0.4
          }
        },
        "printbed": {
          "printbed_heatable": false
        }
      },
      {
        "model": "Anet A2",
        "buildarea_maxdim1": 220,
        "buildarea_maxdim2": 220,
        "form": "cartesian",
        "extruder": {
          "nozzle": {
            "size_id": 0.4
          }
        },
        "printbed": {
          "printbed_heatable": true
        }
      },
      {
        "model": "Anet A2 PLUS",
        "buildarea_maxdim1": 220,
        "buildarea_maxdim2": 270,
        "form": "cartesian",
        "extruder": {
          "nozzle": {
            "size_id": 0.4
          }
        },
        "printbed": {
          "printbed_heatable": true
        }
      },
      {
        "model": "Anet A6",
        "buildarea_maxdim1": 220,
        "buildarea_maxdim2": 220,
        "form": "cartesian",
        "extruder": {
          "nozzle": {
            "size_id": 0.4
          }
        },
        "printbed": {
          "printbed_heatable": true
        }
      },
      {
        "model": "Anet A8",
        "buildarea_maxdim1": 220,
        "buildarea_maxdim2": 220,
        "form": "cartesian",
        "extruder": {
          "nozzle": {
            "size_id": 0.4
          }
        },
        "printbed": {
          "printbed_heatable": true
        }
      },
      {
        "model": "Anet A8 PLUS",
        "buildarea_maxdim1": 300,
        "buildarea_maxdim2": 300,
        "form": "cartesian",
        "extruder": {
          "nozzle": {
            "size_id": 0.4
          }
        },
        "printbed": {
          "printbed_heatable": true
        }
      },
      {
        "model": "Anet E10",
        "buildarea_maxdim1": 220,
        "buildarea_maxdim2": 270,
        "form": "cartesian",
        "extruder": {
          "nozzle": {
            "size_id": 0.4
          }
        },
        "printbed": {
          "printbed_heatable": true
        }
      },
      {
        "model": "Anet E12",
        "buildarea_maxdim1": 300,
        "buildarea_maxdim2": 300,
        "form": "cartesian",
        "extruder": {
          "nozzle": {
            "size_id": 0.4
          }
        },
        "printbed": {
          "printbed_heatable": true
        }
      },
      {
        "model": "Anet E16",
        "buildarea_maxdim1": 300,
        "buildarea_maxdim2": 300,
        "form": "cartesian",
        "extruder": {
          "nozzle": {
            "size_id": 0.4
          }
        },
        "printbed": {
          "printbed_heatable": true
        }
      },
      {
        "model": "Anet ET4",
        "buildarea_maxdim1": 220,
        "buildarea_maxdim2": 220,
        "form": "cartesian",
        "extruder": {
          "nozzle": {
            "size_id": 0.4
          }
        },
        "printbed": {
          "printbed_heatable": true
        }
      },
      {
        "model": "Anet ET4 PRO",
        "buildarea_maxdim1": 220,
        "buildarea_maxdim2": 220,
        "form": "cartesian",
        "extruder": {
          "nozzle": {
            "size_id": 0.4
          }
        },
        "printbed": {
          "printbed_heatable": true
        }
      },
      {
        "model": "Anet ET4 X",
        "buildarea_maxdim1": 220,
        "buildarea_maxdim2": 220,
        "form": "cartesian",
        "extruder": {
          "nozzle": {
            "size_id": 0.4
          }
        },
        "printbed": {
          "printbed_heatable": true
        }
      },
      {
        "model": "Anet ET5",
        "buildarea_maxdim1": 300,
        "buildarea_maxdim2": 300,
        "form": "cartesian",
        "extruder": {
          "nozzle": {
            "size_id": 0.4
          }
        },
        "printbed": {
          "printbed_heatable": true
        }
      },
      {
        "model": "Anet ET5 X",
        "buildarea_maxdim1": 300,
        "buildarea_maxdim2": 300,
        "form": "cartesian",
        "extruder": {
          "nozzle": {
            "size_id": 0.4
          }
        },
        "printbed": {
          "printbed_heatable": true
        }
      },
      {
        "model": "Anycubic 4Max",
        "buildarea_maxdim1": 220,
        "buildarea_maxdim2": 220,
        "form": "cartesian",
        "extruder": {
          "nozzle": {
            "size_id": 0.4
          }
        },
        "printbed": {
          "printbed_heatable": true
        }
      },
      {
        "model": "Anycubic Chiron",
        "buildarea_maxdim1": 400,
        "buildarea_maxdim2": 400,
        "form": "cartesian",
        "extruder": {
          "nozzle": {
            "size_id": 0.4
          }
        },
        "printbed": {
          "printbed_heatable": true
        }
      },
      {
        "model": "Anycubic i3 Mega",
        "buildarea_maxdim1": 210,
        "buildarea_maxdim2": 210,
        "form": "cartesian",
        "extruder": {
          "nozzle": {
            "size_id": 0.4
          }
        },
        "printbed": {
          "printbed_heatable": true
        }
      },
      {
        "model": "Artemis",
        "buildarea_maxdim1": 290,
        "buildarea_maxdim2": 290,
        "form": "elliptic",
        "extruder": {
          "nozzle": {
            "size_id": 0.5
          }
        },
        "printbed": {
          "printbed_heatable": true
        }
      },
      {
        "model": "BeamUp S",
        "buildarea_maxdim1": 200,
        "buildarea_maxdim2": 180,
        "form": "cartesian",
        "extruder": {
          "nozzle": {
            "size_id": 0.4
          }
        },
        "printbed": {
          "printbed_heatable": false
        }
      },
      {
        "model": "BFB_Test",
        "buildarea_maxdim1": 275,
        "buildarea_maxdim2": 265,
        "form": "cartesian",
        "extruder": {
          "nozzle": {
            "size_id": 0.5
          }
        },
        "printbed": {
          "printbed_heatable": false
        }
      },
      {
        "model": "BIBO2 dual",
        "buildarea_maxdim1": 214,
        "buildarea_maxdim2": 186,
        "form": "cartesian",
        "extruder": {
          "nozzle": {
            "size_id": 0.4
          }
        },
        "printbed": {
          "printbed_heatable": true
        }
      },
      {
        "model": "BQ Hephestos 2",
        "buildarea_maxdim1": 210,
        "buildarea_maxdim2": 297,
        "form": "cartesian",
        "extruder": {
          "nozzle": {
            "size_id": 0.4
          }
        },
        "printbed": {
          "printbed_heatable": false
        }
      },
      {
        "model": "BQ Prusa i3 Hephestos",
        "buildarea_maxdim1": 215,
        "buildarea_maxdim2": 210,
        "form": "cartesian",
        "extruder": {
          "nozzle": {
            "size_id": 0.4
          }
        },
        "printbed": {
          "printbed_heatable": false
        }
      },
      {
        "model": "BQ Prusa i3 Hephestos XL",
        "buildarea_maxdim1": 200,
        "buildarea_maxdim2": 300,
        "form": "cartesian",
        "extruder": {
          "nozzle": {
            "size_id": 0.4
          }
        },
        "printbed": {
          "printbed_heatable": false
        }
      },
      {
        "model": "BQ Witbox",
        "buildarea_maxdim1": 297,
        "buildarea_maxdim2": 210,
        "form": "cartesian",
        "extruder": {
          "nozzle": {
            "size_id": 0.4
          }
        },
        "printbed": {
          "printbed_heatable": false
        }
      },
      {
        "model": "BQ Witbox 2",
        "buildarea_maxdim1": 297,
        "buildarea_maxdim2": 210,
        "form": "cartesian",
        "extruder": {
          "nozzle": {
            "size_id": 0.4
          }
        },
        "printbed": {
          "printbed_heatable": false
        }
      },
      {
        "model": "Builder Premium Large",
        "buildarea_maxdim1": 215,
        "buildarea_maxdim2": 205,
        "form": "cartesian",
        "extruder": {
          "nozzle": {
            "size_id": 0.4
          }
        },
        "printbed": {
          "printbed_heatable": true
        }
      },
      {
        "model": "Builder Premium Medium",
        "buildarea_maxdim1": 215,
        "buildarea_maxdim2": 205,
        "form": "cartesian",
        "extruder": {
          "nozzle": {
            "size_id": 0.4
          }
        },
        "printbed": {
          "printbed_heatable": true
        }
      },
      {
        "model": "Builder Premium Small",
        "buildarea_maxdim1": 215,
        "buildarea_maxdim2": 205,
        "form": "cartesian",
        "extruder": {
          "nozzle": {
            "size_id": 0.4
          }
        },
        "printbed": {
          "printbed_heatable": true
        }
      },
      {
        "model": "Cocoon Create ModelMaker",
        "buildarea_maxdim1": 120,
        "buildarea_maxdim2": 135,
        "form": "cartesian",
        "extruder": {
          "nozzle": {
            "size_id": 0.4
          }
        },
        "printbed": {
          "printbed_heatable": false
        }
      },
      {
        "model": "Creality CR-10",
        "buildarea_maxdim1": 300,
        "buildarea_maxdim2": 300,
        "form": "cartesian",
        "extruder": {
          "nozzle": {
            "size_id": 0.4
          }
        },
        "printbed": {
          "printbed_heatable": true
        }
      },
      {
        "model": "Creality CR-10 Max",
        "buildarea_maxdim1": 450,
        "buildarea_maxdim2": 450,
        "form": "cartesian",
        "extruder": {
          "nozzle": {
            "size_id": 0.4
          }
        },
        "printbed": {
          "printbed_heatable": true
        }
      },
      {
        "model": "Creality CR-10 Mini",
        "buildarea_maxdim1": 300,
        "buildarea_maxdim2": 220,
        "form": "cartesian",
        "extruder": {
          "nozzle": {
            "size_id": 0.4
          }
        },
        "printbed": {
          "printbed_heatable": true
        }
      },
      {
        "model": "Creality CR-10S",
        "buildarea_maxdim1": 300,
        "buildarea_maxdim2": 300,
        "form": "cartesian",
        "extruder": {
          "nozzle": {
            "size_id": 0.4
          }
        },
        "printbed": {
          "printbed_heatable": true
        }
      },
      {
        "model": "Creality CR-10S Pro",
        "buildarea_maxdim1": 300,
        "buildarea_maxdim2": 300,
        "form": "cartesian",
        "extruder": {
          "nozzle": {
            "size_id": 0.4
          }
        },
        "printbed": {
          "printbed_heatable": true
        }
      },
      {
        "model": "Creality CR-10S4",
        "buildarea_maxdim1": 400,
        "buildarea_maxdim2": 400,
        "form": "cartesian",
        "extruder": {
          "nozzle": {
            "size_id": 0.4
          }
        },
        "printbed": {
          "printbed_heatable": true
        }
      },
      {
        "model": "Creality CR-10S5",
        "buildarea_maxdim1": 500,
        "buildarea_maxdim2": 500,
        "form": "cartesian",
        "extruder": {
          "nozzle": {
            "size_id": 0.4
          }
        },
        "printbed": {
          "printbed_heatable": true
        }
      },
      {
        "model": "Creality CR-20",
        "buildarea_maxdim1": 220,
        "buildarea_maxdim2": 220,
        "form": "cartesian",
        "extruder": {
          "nozzle": {
            "size_id": 0.4
          }
        },
        "printbed": {
          "printbed_heatable": true
        }
      },
      {
        "model": "Creality CR-20 Pro",
        "buildarea_maxdim1": 220,
        "buildarea_maxdim2": 220,
        "form": "cartesian",
        "extruder": {
          "nozzle": {
            "size_id": 0.4
          }
        },
        "printbed": {
          "printbed_heatable": true
        }
      },
      {
        "model": "Creality CR-X",
        "buildarea_maxdim1": 300,
        "buildarea_maxdim2": 300,
        "form": "cartesian",
        "extruder": {
          "nozzle": {
            "size_id": 0.4
          }
        },
        "printbed": {
          "printbed_heatable": true
        }
      },
      {
        "model": "Creality Ender-2",
        "buildarea_maxdim1": 150,
        "buildarea_maxdim2": 150,
        "form": "cartesian",
        "extruder": {
          "nozzle": {
            "size_id": 0.4
          }
        },
        "printbed": {
          "printbed_heatable": true
        }
      },
      {
        "model": "Creality Ender-3",
        "buildarea_maxdim1": 235,
        "buildarea_maxdim2": 235,
        "form": "cartesian",
        "extruder": {
          "nozzle": {
            "size_id": 0.4
          }
        },
        "printbed": {
          "printbed_heatable": true
        }
      },
      {
        "model": "Creality Ender-4",
        "buildarea_maxdim1": 452,
        "buildarea_maxdim2": 468,
        "form": "cartesian",
        "extruder": {
          "nozzle": {
            "size_id": 0.4
          }
        },
        "printbed": {
          "printbed_heatable": true
        }
      },
      {
        "model": "Creality Ender-5",
        "buildarea_maxdim1": 220,
        "buildarea_maxdim2": 220,
        "form": "cartesian",
        "extruder": {
          "nozzle": {
            "size_id": 0.4
          }
        },
        "printbed": {
          "printbed_heatable": true
        }
      },
      {
        "model": "Creality Ender-5 Plus",
        "buildarea_maxdim1": 350,
        "buildarea_maxdim2": 350,
        "form": "cartesian",
        "extruder": {
          "nozzle": {
            "size_id": 0.4
          }
        },
        "printbed": {
          "printbed_heatable": true
        }
      },
      {
        "model": "Creatable D3",
        "buildarea_maxdim1": 250,
        "buildarea_maxdim2": 250,
        "form": "elliptic",
        "extruder": {
          "nozzle": {
            "size_id": 0.4
          }
        },
        "printbed": {
          "printbed_heatable": true
        }
      },
      {
        "model": "Creawsome Base Printer",
        "buildarea_maxdim1": 100,
        "buildarea_maxdim2": 100,
        "form": "cartesian",
        "extruder": {
          "nozzle": {
            "size_id": 0.4
          }
        },
        "printbed": {
          "printbed_heatable": true
        }
      },
      {
        "model": "Cubicon Dual Pro-A30",
        "buildarea_maxdim1": 300,
        "buildarea_maxdim2": 300,
        "form": "cartesian",
        "extruder": {
          "nozzle": {
            "size_id": 0.4
          }
        },
        "printbed": {
          "printbed_heatable": true
        }
      },
      {
        "model": "Cubicon Single",
        "buildarea_maxdim1": 240,
        "buildarea_maxdim2": 190,
        "form": "cartesian",
        "extruder": {
          "nozzle": {
            "size_id": 0.4
          }
        },
        "printbed": {
          "printbed_heatable": true
        }
      },
      {
        "model": "Cubicon Single Plus",
        "buildarea_maxdim1": 240,
        "buildarea_maxdim2": 190,
        "form": "cartesian",
        "extruder": {
          "nozzle": {
            "size_id": 0.4
          }
        },
        "printbed": {
          "printbed_heatable": true
        }
      },
      {
        "model": "Cubicon Style",
        "buildarea_maxdim1": 150,
        "buildarea_maxdim2": 150,
        "form": "cartesian",
        "extruder": {
          "nozzle": {
            "size_id": 0.4
          }
        },
        "printbed": {
          "printbed_heatable": true
        }
      },
      {
        "model": "Cubicon Style Plus-A15",
        "buildarea_maxdim1": 150,
        "buildarea_maxdim2": 150,
        "form": "cartesian",
        "extruder": {
          "nozzle": {
            "size_id": 0.4
          }
        },
        "printbed": {
          "printbed_heatable": true
        }
      },
      {
        "model": "Delta Go",
        "buildarea_maxdim1": 115,
        "buildarea_maxdim2": 115,
        "form": "elliptic",
        "extruder": {
          "nozzle": {
            "size_id": 0.4
          }
        },
        "printbed": {
          "printbed_heatable": false
        }
      },
      {
        "model": "DeltaBot style",
        "buildarea_maxdim1": 150,
        "buildarea_maxdim2": 150,
        "form": "elliptic",
        "extruder": {
          "nozzle": {
            "size_id": 0.5
          }
        },
        "printbed": {
          "printbed_heatable": true
        }
      },
      {
        "model": "Discov3ry Complete (Ultimaker 2+)",
        "buildarea_maxdim1": 205,
        "buildarea_maxdim2": 205,
        "form": "cartesian",
        "extruder": {
          "nozzle": {
            "size_id": 0.84
          }
        },
        "printbed": {
          "printbed_heatable": false
        }
      },
      {
        "model": "Erzay3D",
        "buildarea_maxdim1": 210,
        "buildarea_maxdim2": 210,
        "form": "elliptic",
        "extruder": {
          "nozzle": {
            "size_id": 0.4
          }
        },
        "printbed": {
          "printbed_heatable": true
        }
      },
      {
        "model": "FABtotum Personal Fabricator",
        "buildarea_maxdim1": 214,
        "buildarea_maxdim2": 234,
        "form": "cartesian",
        "extruder": {
          "nozzle": {
            "size_id": 0.4
          }
        },
        "printbed": {
          "printbed_heatable": true
        }
      },
      {
        "model": "FelixPro2Dual",
        "buildarea_maxdim1": 240,
        "buildarea_maxdim2": 225,
        "form": "cartesian",
        "extruder": {
          "nozzle": {
            "size_id": 0.35
          }
        },
        "printbed": {
          "printbed_heatable": true
        }
      },
      {
        "model": "FelixTec4Dual",
        "buildarea_maxdim1": 255,
        "buildarea_maxdim2": 205,
        "form": "cartesian",
        "extruder": {
          "nozzle": {
            "size_id": 0.35
          }
        },
        "printbed": {
          "printbed_heatable": true
        }
      },
      {
        "model": "Geeetech A30",
        "buildarea_maxdim1": 320,
        "buildarea_maxdim2": 320,
        "form": "cartesian",
        "extruder": {
          "nozzle": {
            "size_id": 0.4
          }
        },
        "printbed": {
          "printbed_heatable": true
        }
      },
      {
        "model": "German RepRap Neo",
        "buildarea_maxdim1": 150,
        "buildarea_maxdim2": 150,
        "form": "cartesian",
        "extruder": {
          "nozzle": {
            "size_id": 0.5
          }
        },
        "printbed": {
          "printbed_heatable": false
        }
      },
      {
        "model": "gMax 1.5 Plus",
        "buildarea_maxdim1": 406,
        "buildarea_maxdim2": 406,
        "form": "cartesian",
        "extruder": {
          "nozzle": {
            "size_id": 0.5
          }
        },
        "printbed": {
          "printbed_heatable": false
        }
      },
      {
        "model": "gMax 1.5 Plus Dual Extruder",
        "buildarea_maxdim1": 406,
        "buildarea_maxdim2": 406,
        "form": "cartesian",
        "extruder": {
          "nozzle": {
            "size_id": 0.5
          }
        },
        "printbed": {
          "printbed_heatable": false
        }
      },
      {
        "model": "Hellbot Adonis",
        "buildarea_maxdim1": 160,
        "buildarea_maxdim2": 160,
        "form": "cartesian",
        "extruder": {
          "nozzle": {
            "size_id": 0.4
          }
        },
        "printbed": {
          "printbed_heatable": false
        }
      },
      {
        "model": "Hellbot Magna 1",
        "buildarea_maxdim1": 220,
        "buildarea_maxdim2": 220,
        "form": "cartesian",
        "extruder": {
          "nozzle": {
            "size_id": 0.4
          }
        },
        "printbed": {
          "printbed_heatable": false
        }
      },
      {
        "model": "Hellbot Magna DUAL",
        "buildarea_maxdim1": 220,
        "buildarea_maxdim2": 220,
        "form": "cartesian",
        "extruder": {
          "nozzle": {
            "size_id": 0.4
          }
        },
        "printbed": {
          "printbed_heatable": false
        }
      },
      {
        "model": "hello BEE prusa",
        "buildarea_maxdim1": 185,
        "buildarea_maxdim2": 200,
        "form": "cartesian",
        "extruder": {
          "nozzle": {
            "size_id": 0.4
          }
        },
        "printbed": {
          "printbed_heatable": true
        }
      },
      {
        "model": "IMADE3D JellyBOX 2",
        "buildarea_maxdim1": 180,
        "buildarea_maxdim2": 165,
        "form": "cartesian",
        "extruder": {
          "nozzle": {
            "size_id": 0.4
          }
        },
        "printbed": {
          "printbed_heatable": true
        }
      },
      {
        "model": "IMADE3D JellyBOX Original",
        "buildarea_maxdim1": 170,
        "buildarea_maxdim2": 160,
        "form": "cartesian",
        "extruder": {
          "nozzle": {
            "size_id": 0.4
          }
        },
        "printbed": {
          "printbed_heatable": true
        }
      },
      {
        "model": "Innovo INVENTOR",
        "buildarea_maxdim1": 340,
        "buildarea_maxdim2": 300,
        "form": "cartesian",
        "extruder": {
          "nozzle": {
            "size_id": 0.4
          }
        },
        "printbed": {
          "printbed_heatable": true
        }
      },
      {
        "model": "JGAurora A1",
        "buildarea_maxdim1": 300,
        "buildarea_maxdim2": 300,
        "form": "cartesian",
        "extruder": {
          "nozzle": {
            "size_id": 0.4
          }
        },
        "printbed": {
          "printbed_heatable": true
        }
      },
      {
        "model": "JGAurora A3S",
        "buildarea_maxdim1": 205,
        "buildarea_maxdim2": 205,
        "form": "cartesian",
        "extruder": {
          "nozzle": {
            "size_id": 0.4
          }
        },
        "printbed": {
          "printbed_heatable": true
        }
      },
      {
        "model": "JGAurora A5 & A5S",
        "buildarea_maxdim1": 300,
        "buildarea_maxdim2": 300,
        "form": "cartesian",
        "extruder": {
          "nozzle": {
            "size_id": 0.4
          }
        },
        "printbed": {
          "printbed_heatable": true
        }
      },
      {
        "model": "JGAurora JGMaker Magic",
        "buildarea_maxdim1": 220,
        "buildarea_maxdim2": 220,
        "form": "cartesian",
        "extruder": {
          "nozzle": {
            "size_id": 0.4
          }
        },
        "printbed": {
          "printbed_heatable": true
        }
      },
      {
        "model": "JGAurora Z-603S",
        "buildarea_maxdim1": 280,
        "buildarea_maxdim2": 180,
        "form": "cartesian",
        "extruder": {
          "nozzle": {
            "size_id": 0.4
          }
        },
        "printbed": {
          "printbed_heatable": true
        }
      },
      {
        "model": "Julia V2",
        "buildarea_maxdim1": 210,
        "buildarea_maxdim2": 250,
        "form": "cartesian",
        "extruder": {
          "nozzle": {
            "size_id": 0.4
          }
        },
        "printbed": {
          "printbed_heatable": true
        }
      },
      {
        "model": "Kemiq Q2 Beta",
        "buildarea_maxdim1": 190,
        "buildarea_maxdim2": 200,
        "form": "cartesian",
        "extruder": {
          "nozzle": {
            "size_id": 0.4
          }
        },
        "printbed": {
          "printbed_heatable": true
        }
      },
      {
        "model": "Kemiq Q2 Gama",
        "buildarea_maxdim1": 190,
        "buildarea_maxdim2": 200,
        "form": "cartesian",
        "extruder": {
          "nozzle": {
            "size_id": 0.4
          }
        },
        "printbed": {
          "printbed_heatable": false
        }
      },
      {
        "model": "KUPIDO",
        "buildarea_maxdim1": 195,
        "buildarea_maxdim2": 195,
        "form": "cartesian",
        "extruder": {
          "nozzle": {
            "size_id": 0.4
          }
        },
        "printbed": {
          "printbed_heatable": true
        }
      },
      {
        "model": "Leapfrog Bolt Pro",
        "buildarea_maxdim1": 302,
        "buildarea_maxdim2": 322,
        "form": "cartesian",
        "extruder": {
          "nozzle": {
            "size_id": 0.4
          }
        },
        "printbed": {
          "printbed_heatable": true
        }
      },
      {
        "model": "Lotmaxx SC-10",
        "buildarea_maxdim1": 235,
        "buildarea_maxdim2": 235,
        "form": "cartesian",
        "extruder": {
          "nozzle": {
            "size_id": 0.4
          }
        },
        "printbed": {
          "printbed_heatable": true
        }
      },
      {
        "model": "Lotmaxx SC-20",
        "buildarea_maxdim1": 235,
        "buildarea_maxdim2": 235,
        "form": "cartesian",
        "extruder": {
          "nozzle": {
            "size_id": 0.4
          }
        },
        "printbed": {
          "printbed_heatable": true
        }
      },
      {
        "model": "Makeblock mCreate",
        "buildarea_maxdim1": 225,
        "buildarea_maxdim2": 225,
        "form": "cartesian",
        "extruder": {
          "nozzle": {
            "size_id": 0.4
          }
        },
        "printbed": {
          "printbed_heatable": true
        }
      },
      {
        "model": "MAKEiT Pro-L",
        "buildarea_maxdim1": 305,
        "buildarea_maxdim2": 254,
        "form": "cartesian",
        "extruder": {
          "nozzle": {
            "size_id": 0.4
          }
        },
        "printbed": {
          "printbed_heatable": true
        }
      },
      {
        "model": "MAKEiT Pro-M",
        "buildarea_maxdim1": 200,
        "buildarea_maxdim2": 240,
        "form": "cartesian",
        "extruder": {
          "nozzle": {
            "size_id": 0.4
          }
        },
        "printbed": {
          "printbed_heatable": true
        }
      },
      {
        "model": "makeR Pegasus",
        "buildarea_maxdim1": 400,
        "buildarea_maxdim2": 400,
        "form": "cartesian",
        "extruder": {
          "nozzle": {
            "size_id": 0.4
          }
        },
        "printbed": {
          "printbed_heatable": true
        }
      },
      {
        "model": "makeR Prusa Tairona I3",
        "buildarea_maxdim1": 200,
        "buildarea_maxdim2": 200,
        "form": "cartesian",
        "extruder": {
          "nozzle": {
            "size_id": 0.4
          }
        },
        "printbed": {
          "printbed_heatable": true
        }
      },
      {
        "model": "MakerBot Replicator",
        "buildarea_maxdim1": 225,
        "buildarea_maxdim2": 145,
        "form": "cartesian",
        "extruder": {
          "nozzle": {
            "size_id": 0.4
          }
        },
        "printbed": {
          "printbed_heatable": true
        }
      },
      {
        "model": "Malyan M180",
        "buildarea_maxdim1": 230,
        "buildarea_maxdim2": 145,
        "form": "cartesian",
        "extruder": {
          "nozzle": {
            "size_id": 0.4
          }
        },
        "printbed": {
          "printbed_heatable": false
        }
      },
      {
        "model": "Malyan M200",
        "buildarea_maxdim1": 120,
        "buildarea_maxdim2": 120,
        "form": "cartesian",
        "extruder": {
          "nozzle": {
            "size_id": 0.4
          }
        },
        "printbed": {
          "printbed_heatable": true
        }
      },
      {
        "model": "Mankati Fullscale XT Plus",
        "buildarea_maxdim1": 260,
        "buildarea_maxdim2": 260,
        "form": "cartesian",
        "extruder": {
          "nozzle": {
            "size_id": 0.4
          }
        },
        "printbed": {
          "printbed_heatable": true
        }
      },
      {
        "model": "Mark2_for_Ultimaker2",
        "buildarea_maxdim1": 223,
        "buildarea_maxdim2": 223,
        "form": "cartesian",
        "extruder": {
          "nozzle": {
            "size_id": 0.4
          }
        },
        "printbed": {
          "printbed_heatable": true
        }
      },
      {
        "model": "Mendel90",
        "buildarea_maxdim1": 200,
        "buildarea_maxdim2": 200,
        "form": "cartesian",
        "extruder": {
          "nozzle": {
            "size_id": 0.4
          }
        },
        "printbed": {
          "printbed_heatable": true
        }
      },
      {
        "model": "Moai",
        "buildarea_maxdim1": 130,
        "buildarea_maxdim2": 130,
        "form": "cartesian",
        "extruder": {
          "nozzle": {
            "size_id": 0.067
          }
        },
        "printbed": {
          "printbed_heatable": false
        }
      },
      {
        "model": "Monoprice Select Mini V1",
        "buildarea_maxdim1": 120,
        "buildarea_maxdim2": 120,
        "form": "cartesian",
        "extruder": {
          "nozzle": {
            "size_id": 0.4
          }
        },
        "printbed": {
          "printbed_heatable": true
        }
      },
      {
        "model": "Monoprice Select Mini V2",
        "buildarea_maxdim1": 120,
        "buildarea_maxdim2": 120,
        "form": "cartesian",
        "extruder": {
          "nozzle": {
            "size_id": 0.4
          }
        },
        "printbed": {
          "printbed_heatable": true
        }
      },
      {
        "model": "Monoprice Ultimate",
        "buildarea_maxdim1": 200,
        "buildarea_maxdim2": 200,
        "form": "cartesian",
        "extruder": {
          "nozzle": {
            "size_id": 0.4
          }
        },
        "printbed": {
          "printbed_heatable": true
        }
      },
      {
        "model": "Mr Bot 280",
        "buildarea_maxdim1": 275,
        "buildarea_maxdim2": 275,
        "form": "cartesian",
        "extruder": {
          "nozzle": {
            "size_id": 0.4
          }
        },
        "printbed": {
          "printbed_heatable": true
        }
      },
      {
        "model": "NWA3D A31",
        "buildarea_maxdim1": 300,
        "buildarea_maxdim2": 300,
        "form": "cartesian",
        "extruder": {
          "nozzle": {
            "size_id": 0.4
          }
        },
        "printbed": {
          "printbed_heatable": true
        }
      },
      {
        "model": "NWA3D A5",
        "buildarea_maxdim1": 125,
        "buildarea_maxdim2": 150,
        "form": "cartesian",
        "extruder": {
          "nozzle": {
            "size_id": 0.4
          }
        },
        "printbed": {
          "printbed_heatable": false
        }
      },
      {
        "model": "Printrbot Play",
        "buildarea_maxdim1": 100,
        "buildarea_maxdim2": 100,
        "form": "cartesian",
        "extruder": {
          "nozzle": {
            "size_id": 0.4
          }
        },
        "printbed": {
          "printbed_heatable": false
        }
      },
      {
        "model": "Printrbot Play (Heated Bed)",
        "buildarea_maxdim1": 100,
        "buildarea_maxdim2": 203,
        "form": "cartesian",
        "extruder": {
          "nozzle": {
            "size_id": 0.4
          }
        },
        "printbed": {
          "printbed_heatable": true
        }
      },
      {
        "model": "Printrbot Simple",
        "buildarea_maxdim1": 150,
        "buildarea_maxdim2": 140,
        "form": "cartesian",
        "extruder": {
          "nozzle": {
            "size_id": 0.4
          }
        },
        "printbed": {
          "printbed_heatable": false
        }
      },
      {
        "model": "Printrbot Simple Maker's Kit (1405)",
        "buildarea_maxdim1": 100,
        "buildarea_maxdim2": 100,
        "form": "cartesian",
        "extruder": {
          "nozzle": {
            "size_id": 0.4
          }
        },
        "printbed": {
          "printbed_heatable": false
        }
      },
      {
        "model": "Printrbot Simple Metal Extended",
        "buildarea_maxdim1": 250,
        "buildarea_maxdim2": 150,
        "form": "cartesian",
        "extruder": {
          "nozzle": {
            "size_id": 0.4
          }
        },
        "printbed": {
          "printbed_heatable": true
        }
      },
      {
        "model": "Prusa i3",
        "buildarea_maxdim1": 200,
        "buildarea_maxdim2": 200,
        "form": "cartesian",
        "extruder": {
          "nozzle": {
            "size_id": 0.4
          }
        },
        "printbed": {
          "printbed_heatable": true
        }
      },
      {
        "model": "Prusa i3 Mk2",
        "buildarea_maxdim1": 250,
        "buildarea_maxdim2": 210,
        "form": "cartesian",
        "extruder": {
          "nozzle": {
            "size_id": 0.4
          }
        },
        "printbed": {
          "printbed_heatable": true
        }
      },
      {
        "model": "Prusa i3 Mk3/Mk3s",
        "buildarea_maxdim1": 250,
        "buildarea_maxdim2": 210,
        "form": "cartesian",
        "extruder": {
          "nozzle": {
            "size_id": 0.4
          }
        },
        "printbed": {
          "printbed_heatable": true
        }
      },
      {
        "model": "Prusa i3 xl",
        "buildarea_maxdim1": 200,
        "buildarea_maxdim2": 270,
        "form": "cartesian",
        "extruder": {
          "nozzle": {
            "size_id": 0.4
          }
        },
        "printbed": {
          "printbed_heatable": true
        }
      },
      {
        "model": "Punchtec Connect XL",
        "buildarea_maxdim1": 304,
        "buildarea_maxdim2": 304,
        "form": "cartesian",
        "extruder": {
          "nozzle": {
            "size_id": 0.4
          }
        },
        "printbed": {
          "printbed_heatable": true
        }
      },
      {
        "model": "Raise3D N2 Dual",
        "buildarea_maxdim1": 305,
        "buildarea_maxdim2": 305,
        "form": "cartesian",
        "extruder": {
          "nozzle": {
            "size_id": 0.4
          }
        },
        "printbed": {
          "printbed_heatable": true
        }
      },
      {
        "model": "Raise3D N2 Plus Dual",
        "buildarea_maxdim1": 305,
        "buildarea_maxdim2": 305,
        "form": "cartesian",
        "extruder": {
          "nozzle": {
            "size_id": 0.4
          }
        },
        "printbed": {
          "printbed_heatable": true
        }
      },
      {
        "model": "Raise3D N2 Plus Single",
        "buildarea_maxdim1": 305,
        "buildarea_maxdim2": 305,
        "form": "cartesian",
        "extruder": {
          "nozzle": {
            "size_id": 0.4
          }
        },
        "printbed": {
          "printbed_heatable": true
        }
      },
      {
        "model": "Raise3D N2 Single",
        "buildarea_maxdim1": 305,
        "buildarea_maxdim2": 305,
        "form": "cartesian",
        "extruder": {
          "nozzle": {
            "size_id": 0.4
          }
        },
        "printbed": {
          "printbed_heatable": true
        }
      },
      {
        "model": "Renkforce RF100",
        "buildarea_maxdim1": "100",
        "buildarea_maxdim2": "100",
        "form": "cartesian",
        "extruder": {
          "nozzle": {
            "size_id": 0.4
          }
        },
        "printbed": {
          "printbed_heatable": false
        }
      },
      {
        "model": "Rigid3D",
        "buildarea_maxdim1": 250,
        "buildarea_maxdim2": 250,
        "form": "cartesian",
        "extruder": {
          "nozzle": {
            "size_id": 0.4
          }
        },
        "printbed": {
          "printbed_heatable": true
        }
      },
      {
        "model": "Rigid3D 3rd Geneartion",
        "buildarea_maxdim1": 275,
        "buildarea_maxdim2": 290,
        "form": "cartesian",
        "extruder": {
          "nozzle": {
            "size_id": 0.4
          }
        },
        "printbed": {
          "printbed_heatable": true
        }
      },
      {
        "model": "Rigid3D Hobby",
        "buildarea_maxdim1": 150,
        "buildarea_maxdim2": 150,
        "form": "cartesian",
        "extruder": {
          "nozzle": {
            "size_id": 0.4
          }
        },
        "printbed": {
          "printbed_heatable": false
        }
      },
      {
        "model": "Rigid3D Mucit",
        "buildarea_maxdim1": 150,
        "buildarea_maxdim2": 150,
        "form": "cartesian",
        "extruder": {
          "nozzle": {
            "size_id": 0.4
          }
        },
        "printbed": {
          "printbed_heatable": false
        }
      },
      {
        "model": "Rigid3D Zero",
        "buildarea_maxdim1": 250,
        "buildarea_maxdim2": 250,
        "form": "cartesian",
        "extruder": {
          "nozzle": {
            "size_id": 0.4
          }
        },
        "printbed": {
          "printbed_heatable": false
        }
      },
      {
        "model": "Rigid3D Zero2",
        "buildarea_maxdim1": 200,
        "buildarea_maxdim2": 200,
        "form": "cartesian",
        "extruder": {
          "nozzle": {
            "size_id": 0.4
          }
        },
        "printbed": {
          "printbed_heatable": true
        }
      },
      {
        "model": "RigidBot",
        "buildarea_maxdim1": 254,
        "buildarea_maxdim2": 254,
        "form": "cartesian",
        "extruder": {
          "nozzle": {
            "size_id": 0.4
          }
        },
        "printbed": {
          "printbed_heatable": true
        }
      },
      {
        "model": "RigidBotBig",
        "buildarea_maxdim1": 400,
        "buildarea_maxdim2": 300,
        "form": "cartesian",
        "extruder": {
          "nozzle": {
            "size_id": 0.4
          }
        },
        "printbed": {
          "printbed_heatable": true
        }
      },
      {
        "model": "ROBO 3D R1",
        "buildarea_maxdim1": 225,
        "buildarea_maxdim2": 245,
        "form": "cartesian",
        "extruder": {
          "nozzle": {
            "size_id": 0.4
          }
        },
        "printbed": {
          "printbed_heatable": true
        }
      },
      {
        "model": "Rostock Max V3.2",
        "buildarea_maxdim1": 265,
        "buildarea_maxdim2": 265,
        "form": "elliptic",
        "extruder": {
          "nozzle": {
            "size_id": 0.5
          }
        },
        "printbed": {
          "printbed_heatable": true
        }
      },
      {
        "model": "RoVa3D",
        "buildarea_maxdim1": 215,
        "buildarea_maxdim2": 250,
        "form": "cartesian",
        "extruder": {
          "nozzle": {
            "size_id": 0.35
          }
        },
        "printbed": {
          "printbed_heatable": true
        }
      },
      {
        "model": "Stereotech STE320",
        "buildarea_maxdim1": 218,
        "buildarea_maxdim2": 210,
        "form": "cartesian",
        "extruder": {
          "nozzle": {
            "size_id": 0.4
          }
        },
        "printbed": {
          "printbed_heatable": true
        }
      },
      {
        "model": "Strateo3D",
        "buildarea_maxdim1": 600,
        "buildarea_maxdim2": 420,
        "form": "cartesian",
        "extruder": {
          "nozzle": {
            "size_id": 0.4
          }
        },
        "printbed": {
          "printbed_heatable": true
        }
      },
      {
        "model": "Tevo Black Widow",
        "buildarea_maxdim1": 350,
        "buildarea_maxdim2": 250,
        "form": "cartesian",
        "extruder": {
          "nozzle": {
            "size_id": 0.4
          }
        },
        "printbed": {
          "printbed_heatable": true
        }
      },
      {
        "model": "Tevo Tarantula",
        "buildarea_maxdim1": 200,
        "buildarea_maxdim2": 200,
        "form": "cartesian",
        "extruder": {
          "nozzle": {
            "size_id": 0.4
          }
        },
        "printbed": {
          "printbed_heatable": true
        }
      },
      {
        "model": "Tevo Tornado",
        "buildarea_maxdim1": 300,
        "buildarea_maxdim2": 300,
        "form": "cartesian",
        "extruder": {
          "nozzle": {
            "size_id": 0.4
          }
        },
        "printbed": {
          "printbed_heatable": true
        }
      },
      {
        "model": "TiZYX K25",
        "buildarea_maxdim1": 255,
        "buildarea_maxdim2": 255,
        "form": "cartesian",
        "extruder": {
          "nozzle": {
            "size_id": 0.4
          }
        },
        "printbed": {
          "printbed_heatable": true
        }
      },
      {
        "model": "TypeAMachines",
        "buildarea_maxdim1": 305,
        "buildarea_maxdim2": 305,
        "form": "cartesian",
        "extruder": {
          "nozzle": {
            "size_id": 0.4
          }
        },
        "printbed": {
          "printbed_heatable": true
        }
      },
      {
        "model": "Tyro",
        "buildarea_maxdim1": 150,
        "buildarea_maxdim2": 150,
        "form": "cartesian",
        "extruder": {
          "nozzle": {
            "size_id": 0.4
          }
        },
        "printbed": {
          "printbed_heatable": false
        }
      },
      {
        "model": "Ultimaker 2",
        "buildarea_maxdim1": 223,
        "buildarea_maxdim2": 223,
        "form": "cartesian",
        "extruder": {
          "nozzle": {
            "size_id": 0.4
          }
        },
        "printbed": {
          "printbed_heatable": true
        }
      },
      {
        "model": "Ultimaker 2 Extended",
        "buildarea_maxdim1": 223,
        "buildarea_maxdim2": 223,
        "form": "cartesian",
        "extruder": {
          "nozzle": {
            "size_id": 0.4
          }
        },
        "printbed": {
          "printbed_heatable": true
        }
      },
      {
        "model": "Ultimaker 2 Extended with Olsson",
        "buildarea_maxdim1": 223,
        "buildarea_maxdim2": 223,
        "form": "cartesian",
        "extruder": {
          "nozzle": {
            "size_id": 0.4
          }
        },
        "printbed": {
          "printbed_heatable": true
        }
      },
      {
        "model": "Ultimaker 2 Extended+",
        "buildarea_maxdim1": 223,
        "buildarea_maxdim2": 223,
        "form": "cartesian",
        "extruder": {
          "nozzle": {
            "size_id": 0.4
          }
        },
        "printbed": {
          "printbed_heatable": true
        }
      },
      {
        "model": "Ultimaker 2 Go",
        "buildarea_maxdim1": 120,
        "buildarea_maxdim2": 120,
        "form": "cartesian",
        "extruder": {
          "nozzle": {
            "size_id": 0.4
          }
        },
        "printbed": {
          "printbed_heatable": false
        }
      },
      {
        "model": "Ultimaker 2 with Olsson Block",
        "buildarea_maxdim1": 223,
        "buildarea_maxdim2": 223,
        "form": "cartesian",
        "extruder": {
          "nozzle": {
            "size_id": 0.4
          }
        },
        "printbed": {
          "printbed_heatable": true
        }
      },
      {
        "model": "Ultimaker 2+",
        "buildarea_maxdim1": 223,
        "buildarea_maxdim2": 223,
        "form": "cartesian",
        "extruder": {
          "nozzle": {
            "size_id": 0.4
          }
        },
        "printbed": {
          "printbed_heatable": true
        }
      },
      {
        "model": "Ultimaker 3",
        "buildarea_maxdim1": 233,
        "buildarea_maxdim2": 215,
        "form": "cartesian",
        "extruder": {
          "nozzle": {
            "size_id": 0.4
          }
        },
        "printbed": {
          "printbed_heatable": true
        }
      },
      {
        "model": "Ultimaker 3 Extended",
        "buildarea_maxdim1": 233,
        "buildarea_maxdim2": 215,
        "form": "cartesian",
        "extruder": {
          "nozzle": {
            "size_id": 0.4
          }
        },
        "printbed": {
          "printbed_heatable": true
        }
      },
      {
        "model": "Ultimaker Original",
        "buildarea_maxdim1": 205,
        "buildarea_maxdim2": 195,
        "form": "cartesian",
        "extruder": {
          "nozzle": {
            "size_id": 0.4
          }
        },
        "printbed": {
          "printbed_heatable": false
        }
      },
      {
        "model": "Ultimaker Original",
        "buildarea_maxdim1": 205,
        "buildarea_maxdim2": 205,
        "form": "cartesian",
        "extruder": {
          "nozzle": {
            "size_id": 0.4
          }
        },
        "printbed": {
          "printbed_heatable": false
        }
      },
      {
        "model": "Ultimaker Original+",
        "buildarea_maxdim1": 205,
        "buildarea_maxdim2": 205,
        "form": "cartesian",
        "extruder": {
          "nozzle": {
            "size_id": 0.4
          }
        },
        "printbed": {
          "printbed_heatable": true
        }
      },
      {
        "model": "Ultimaker S3",
        "buildarea_maxdim1": 230,
        "buildarea_maxdim2": 190,
        "form": "cartesian",
        "extruder": {
          "nozzle": {
            "size_id": 0.4
          }
        },
        "printbed": {
          "printbed_heatable": true
        }
      },
      {
        "model": "Ultimaker S5",
        "buildarea_maxdim1": 330,
        "buildarea_maxdim2": 240,
        "form": "cartesian",
        "extruder": {
          "nozzle": {
            "size_id": 0.4
          }
        },
        "printbed": {
          "printbed_heatable": true
        }
      },
      {
        "model": "UNI-PRINT-3D",
        "buildarea_maxdim1": 186,
        "buildarea_maxdim2": 220,
        "form": "cartesian",
        "extruder": {
          "nozzle": {
            "size_id": 0.4
          }
        },
        "printbed": {
          "printbed_heatable": true
        }
      },
      {
        "model": "Uniqbot",
        "buildarea_maxdim1": 140,
        "buildarea_maxdim2": 160,
        "form": "cartesian",
        "extruder": {
          "nozzle": {
            "size_id": 0.5
          }
        },
        "printbed": {
          "printbed_heatable": false
        }
      },
      {
        "model": "Vertex K8400",
        "buildarea_maxdim1": 200,
        "buildarea_maxdim2": 200,
        "form": "cartesian",
        "extruder": {
          "nozzle": {
            "size_id": 0.35
          }
        },
        "printbed": {
          "printbed_heatable": true
        }
      },
      {
        "model": "Vertex K8400 Dual",
        "buildarea_maxdim1": 223.7,
        "buildarea_maxdim2": 200,
        "form": "cartesian",
        "extruder": {
          "nozzle": {
            "size_id": 0.35
          }
        },
        "printbed": {
          "printbed_heatable": true
        }
      },
      {
        "model": "Vertex K8600",
        "buildarea_maxdim1": 80,
        "buildarea_maxdim2": 80,
        "form": "cartesian",
        "extruder": {
          "nozzle": {
            "size_id": 0.35
          }
        },
        "printbed": {
          "printbed_heatable": false
        }
      },
      {
        "model": "VORON2",
        "buildarea_maxdim1": 250,
        "buildarea_maxdim2": 250,
        "form": "cartesian",
        "extruder": {
          "nozzle": {
            "size_id": 0.4
          }
        },
        "printbed": {
          "printbed_heatable": true
        }
      },
      {
        "model": "VORON2 250",
        "buildarea_maxdim1": 250,
        "buildarea_maxdim2": 250,
        "form": "cartesian",
        "extruder": {
          "nozzle": {
            "size_id": 0.4
          }
        },
        "printbed": {
          "printbed_heatable": true
        }
      },
      {
        "model": "VORON2 300",
        "buildarea_maxdim1": 300,
        "buildarea_maxdim2": 300,
        "form": "cartesian",
        "extruder": {
          "nozzle": {
            "size_id": 0.4
          }
        },
        "printbed": {
          "printbed_heatable": true
        }
      },
      {
        "model": "VORON2 350",
        "buildarea_maxdim1": 350,
        "buildarea_maxdim2": 350,
        "form": "cartesian",
        "extruder": {
          "nozzle": {
            "size_id": 0.4
          }
        },
        "printbed": {
          "printbed_heatable": true
        }
      },
      {
        "model": "VORON2 Custom",
        "buildarea_maxdim1": 250,
        "buildarea_maxdim2": 250,
        "form": "cartesian",
        "extruder": {
          "nozzle": {
            "size_id": 0.4
          }
        },
        "printbed": {
          "printbed_heatable": true
        }
      },
      {
        "model": "Wanhao Duplicator 4S",
        "buildarea_maxdim1": 225,
        "buildarea_maxdim2": 150,
        "form": "cartesian",
        "extruder": {
          "nozzle": {
            "size_id": 0.4
          }
        },
        "printbed": {
          "printbed_heatable": true
        }
      },
      {
        "model": "Wanhao Duplicator 5S",
        "buildarea_maxdim1": 300,
        "buildarea_maxdim2": 200,
        "form": "cartesian",
        "extruder": {
          "nozzle": {
            "size_id": 0.4
          }
        },
        "printbed": {
          "printbed_heatable": false
        }
      },
      {
        "model": "Wanhao Duplicator 5S Mini",
        "buildarea_maxdim1": 300,
        "buildarea_maxdim2": 200,
        "form": "cartesian",
        "extruder": {
          "nozzle": {
            "size_id": 0.4
          }
        },
        "printbed": {
          "printbed_heatable": false
        }
      },
      {
        "model": "Wanhao Duplicator 6",
        "buildarea_maxdim1": 200,
        "buildarea_maxdim2": 200,
        "form": "cartesian",
        "extruder": {
          "nozzle": {
            "size_id": 0.4
          }
        },
        "printbed": {
          "printbed_heatable": true
        }
      },
      {
        "model": "Wanhao Duplicator 6 Plus",
        "buildarea_maxdim1": 200,
        "buildarea_maxdim2": 200,
        "form": "cartesian",
        "extruder": {
          "nozzle": {
            "size_id": 0.4
          }
        },
        "printbed": {
          "printbed_heatable": true
        }
      },
      {
        "model": "Wanhao Duplicator 9",
        "buildarea_maxdim1": 300,
        "buildarea_maxdim2": 300,
        "form": "cartesian",
        "extruder": {
          "nozzle": {
            "size_id": 0.4
          }
        },
        "printbed": {
          "printbed_heatable": true
        }
      },
      {
        "model": "Wanhao Duplicator i3",
        "buildarea_maxdim1": 200,
        "buildarea_maxdim2": 200,
        "form": "cartesian",
        "extruder": {
          "nozzle": {
            "size_id": 0.4
          }
        },
        "printbed": {
          "printbed_heatable": true
        }
      },
      {
        "model": "Wanhao Duplicator i3 Mini",
        "buildarea_maxdim1": 110,
        "buildarea_maxdim2": 110,
        "form": "cartesian",
        "extruder": {
          "nozzle": {
            "size_id": 0.4
          }
        },
        "printbed": {
          "printbed_heatable": false
        }
      },
      {
        "model": "Wanhao Duplicator i3 Plus",
        "buildarea_maxdim1": 200,
        "buildarea_maxdim2": 200,
        "form": "cartesian",
        "extruder": {
          "nozzle": {
            "size_id": 0.4
          }
        },
        "printbed": {
          "printbed_heatable": true
        }
      },
      {
        "model": "Winbo Dragon(L)4",
        "buildarea_maxdim1": 615,
        "buildarea_maxdim2": 463,
        "form": "cartesian",
        "extruder": {
          "nozzle": {
            "size_id": 0.8
          }
        },
        "printbed": {
          "printbed_heatable": true
        }
      },
      {
        "model": "Winbo Mini2",
        "buildarea_maxdim1": 205,
        "buildarea_maxdim2": 155,
        "form": "cartesian",
        "extruder": {
          "nozzle": {
            "size_id": 0.4
          }
        },
        "printbed": {
          "printbed_heatable": false
        }
      },
      {
        "model": "Winbo Super Helper 105",
        "buildarea_maxdim1": 108,
        "buildarea_maxdim2": 108,
        "form": "cartesian",
        "extruder": {
          "nozzle": {
            "size_id": 0.4
          }
        },
        "printbed": {
          "printbed_heatable": false
        }
      },
      {
        "model": "Winbo Super Helper 155",
        "buildarea_maxdim1": 158,
        "buildarea_maxdim2": 158,
        "form": "cartesian",
        "extruder": {
          "nozzle": {
            "size_id": 0.4
          }
        },
        "printbed": {
          "printbed_heatable": false
        }
      },
      {
        "model": "Z-Bolt Classic",
        "buildarea_maxdim1": 200,
        "buildarea_maxdim2": 200,
        "form": "cartesian",
        "extruder": {
          "nozzle": {
            "size_id": 0.4
          }
        },
        "printbed": {
          "printbed_heatable": true
        }
      },
      {
        "model": "Z-Bolt Plus",
        "buildarea_maxdim1": 300,
        "buildarea_maxdim2": 200,
        "form": "cartesian",
        "extruder": {
          "nozzle": {
            "size_id": 0.4
          }
        },
        "printbed": {
          "printbed_heatable": true
        }
      },
      {
        "model": "Zone3D Printer",
        "buildarea_maxdim1": 240,
        "buildarea_maxdim2": 220,
        "form": "cartesian",
        "extruder": {
          "nozzle": {
            "size_id": 0.4
          }
        },
        "printbed": {
          "printbed_heatable": true
        }
      },
      {
        "model": "ZYYX Agile",
        "buildarea_maxdim1": 265,
        "buildarea_maxdim2": 225,
        "form": "cartesian",
        "extruder": {
          "nozzle": {
            "size_id": 0.4
          }
        },
        "printbed": {
          "printbed_heatable": false
        }
      }
    ]
'''


def populate_machine_samples(app, schema_editor):
    db_alias = schema_editor.connection.alias

    User = app.get_model('authentication', 'User')
    Nozzle = app.get_model('session', 'Nozzle')
    Extruder = app.get_model('session', 'Extruder')
    Printbed = app.get_model('session', 'Printbed')
    Chamber = app.get_model('session', 'Chamber')
    Machine = app.get_model('session', 'Machine')

    user = User.objects.create(email=settings.SAMPLE_SESSIONS_OWNER)
    for m in json.loads(MACHINE_SAMPLES):
        nozzle = Nozzle.objects.using(db_alias).create(**m['extruder']['nozzle'])
        m['extruder']['nozzle'] = nozzle
        extruder = Extruder.objects.using(db_alias).create(**m['extruder'])
        m['extruder'] = extruder
        printbed = Printbed.objects.using(db_alias).create(**m['printbed'])
        m['printbed'] = printbed

        Machine.objects.using(db_alias).create(owner=user,
                               chamber=Chamber.objects.create(),
                               **m)


def remove_samples(app, schema_editor):
    db_alias = schema_editor.connection.alias

    User = app.get_model('authentication', 'User')
    Machine = app.get_model('session', 'Machine')
    for u in User.objects.using(db_alias).filter(email=settings.SAMPLE_SESSIONS_OWNER):
        u.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0031_auto_20191218_2055'),
    ]

    operations = [
             migrations.RunPython(populate_machine_samples, remove_samples)
    ]
