# Generated by Django 2.2.4 on 2020-01-15 15:29

from django.db import migrations


def add_cookie_policy(app, schema_editor):
    db_alias = schema_editor.connection.alias

    CookieConsentSettings = app.get_model('django_simple_cookie_consent', 'CookieConsentSettings')
    CookieConsentSettings.objects.using(db_alias).create(**{'message': 'This website uses cookies to ensure you get the best experience on our website.',
                                                            'button_text': 'Got it!',
                                                            'cookie_policy_link': '/privacy',
                                                            'cookie_policy_link_text': 'Learn more',
                                                            'banner_colour': '#252E39',
                                                            'banner_text_colour': '#FFFFFF',
                                                            'button_colour': '#009DE0',
                                                            'button_text_colour': '#FFFFFF'})


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0032_populate_sample_printers'),
    ]

    operations = [
             migrations.RunPython(add_cookie_policy)
    ]
