# Generated by Django 2.2.4 on 2020-01-29 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0033_add_default_cookie_policy'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='gcode_footer',
            field=models.TextField(default='M190 S20; set the print bed temperature\nM109 S0 T0; set the extruder temperature\nM106 S0; set the part cooling\nG28; move to the home position\nM84; disable motors'),
        ),
        migrations.AddField(
            model_name='machine',
            name='gcode_header',
            field=models.TextField(default='G28; move to the home position\nG21; unit in mm\nG92 E0; reset extruder\nM83; set extruder to relative mode\nM302 S1; allow cold extrusion'),
        ),
    ]
