# Generated by Django 2.2.4 on 2020-01-29 18:28

from django.db import migrations
import json


DEFAULT_GCODE_HEADER = '''G28; move to the home position
G21; unit in mm
G92 E0; reset extruder
M83; set extruder to relative mode
M302 S1; allow cold extrusion'''


DEFAULT_GCODE_FOOTER = '''M190 S20; set the print bed temperature
M109 S0 T0; set the extruder temperature
M106 S0; set the part cooling
G28; move to the home position
M84; disable motors'''

def attach_header_footer(app, schema_editor):
    db_alias = schema_editor.connection.alias
    Session = app.get_model('session', 'Session')
    for s in Session.objects.using(db_alias).all():
        p = json.loads(s._persistence)
        p['machine'].update(dict(gcode_header=DEFAULT_GCODE_HEADER,
                                 gcode_footer=DEFAULT_GCODE_FOOTER))
        s._persistence = json.dumps(p)
        s.save()

def remove_header_footer(app, schema_editor):
    db_alias = schema_editor.connection.alias
    Session = app.get_model('session', 'Session')
    for s in Session.objects.using(db_alias).all():
        p = json.loads(s._persistence)
        del p['machine']['gcode_header']
        del p['machine']['gcode_footer']
        s._persistence = json.dumps(p)
        s.save()

class Migration(migrations.Migration):

    dependencies = [
        ('session', '0034_auto_20200129_1636'),
    ]

    operations = [
            migrations.RunPython(attach_header_footer, remove_header_footer)
    ]
