# Generated by Django 2.2.4 on 2020-02-10 12:41

from django.db import migrations
import json


def set_session_performer(app, schema_editor):
    db_alias = schema_editor.connection.alias
    Session = app.get_model('session', 'Session')
    for s in Session.objects.using(db_alias).all():
        p = json.loads(s._persistence)
        p['session']['user_id'] = ' '.join([s.owner.first_name, s.owner.last_name])
        s._persistence = json.dumps(p)
        s.save()

def clear_session_performer(app, schema_editor):
    db_alias = schema_editor.connection.alias
    Session = app.get_model('session', 'Session')
    for s in Session.objects.using(db_alias).all():
        p = json.loads(s._persistence)
        p['session']['user_id'] = 'user name'
        s._persistence = json.dumps(p)
        s.save()


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0036_machine_add_structure_offsets'),
    ]

    operations = [
            migrations.RunPython(set_session_performer, clear_session_performer)
    ]
