# Generated by Django 2.2.4 on 2020-03-26 10:54

from django.db import migrations
from django.conf import settings

DEFAULT_GCODE_HEADER = '''G28; move to the home position
G21; unit in mm
G92 E0; reset extruder
M83; set extruder to relative mode
M302 S1; allow cold extrusion'''


DEFAULT_GCODE_FOOTER = '''M190 S20; set the print bed temperature
M109 S0 T0; set the extruder temperature
M106 S0; set the part cooling
G28; move to the home position
M84; disable motors'''


def remove_sample_printer_headers(app, schema_editor):
    db_alias = schema_editor.connection.alias

    User = app.get_model('authentication', 'User')
    Machine = app.get_model('session', 'Machine')

    user = User.objects.using(db_alias).get(email=settings.SAMPLE_SESSIONS_OWNER)
    for m in Machine.objects.using(db_alias).filter(owner=user):
        m.gcode_header = ''
        m.gcode_footer = ''
        m.save()


def add_sample_printer_headers(app, schema_editor):
    db_alias = schema_editor.connection.alias

    User = app.get_model('authentication', 'User')
    Machine = app.get_model('session', 'Machine')

    user = User.objects.using(db_alias).get(email=settings.SAMPLE_SESSIONS_OWNER)
    for m in Machine.objects.using(db_alias).filter(owner=user):
        m.gcode_header = DEFAULT_GCODE_HEADER
        m.gcode_footer = DEFAULT_GCODE_FOOTER
        m.save()

class Migration(migrations.Migration):

    dependencies = [
        ('session', '0038_change_prusa_header_footer'),
    ]

    operations = [
            migrations.RunPython(remove_sample_printer_headers, add_sample_printer_headers)
    ]

