# Generated by Django 2.2.4 on 2020-03-26 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0038_change_prusa_header_footer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='gcode_header',
            field=models.TextField(default='G28; move to the home position\nG21; unit in mm\nG92 E0; reset extruder\nM83; set extruder to relative mode'),
        ),
    ]
