# Generated by Django 2.2.4 on 2020-03-30 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0039_remove_sample_printer_headers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='gcode_footer',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='machine',
            name='gcode_header',
            field=models.TextField(default=''),
        ),
    ]
