# Generated by Django 2.2.4 on 2020-03-31 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0040_set_default_header_footer_20200331_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nozzle',
            name='size_id',
            field=models.DecimalField(decimal_places=2, default=0.4, max_digits=2),
        ),
    ]
