# Generated by Django 2.2.4 on 2020-04-09 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0041_allow_two_decimal_nozzle_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='homing_sequence',
            field=models.TextField(default='G28 ; Move to home position'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='gcode_footer',
            field=models.TextField(default='G28 ; Move to home position\nM84 ; Disable motors'),
        ),
    ]
