# Generated by Django 2.2.4 on 2020-04-09 08:38

from django.db import migrations
from django.conf import settings

def populate_homing_scripts(app, schema_editor):
    db_alias = schema_editor.connection.alias
    Machine = app.get_model('session', 'Machine')

    for machine in Machine.objects.using(db_alias).all():
        home_script = 'G28 ; home all axes'
        footer_homing = 'G28 ; home all axes'
        if 'prusa' in machine.model.lower():
            home_script = 'G28 W ; home all without mesh bed level\nG80 ; mesh bed leveling'
            footer_homing = 'G28 W ; home all axes without mesh leveling'
        machine.homing_sequence = home_script
        if 'G28' not in machine.gcode_footer:
            if 'M84' not in machine.gcode_footer:
                machine.gcode_footer = 'M84 ; disable motors' + '\n' + machine.gcode_footer
            machine.gcode_footer = footer_homing + '\n' + machine.gcode_footer
        machine.save()

def revert_homing_scripts(app, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0042_add_custom_homing_command'),
    ]

    operations = [
            migrations.RunPython(populate_homing_scripts, revert_homing_scripts)
    ]
