# Generated by Django 2.2.4 on 2020-04-19 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0043_populate_homing_scripts'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='notes',
            field=models.CharField(max_length=240, null=True),
        ),
    ]
