# Generated by Django 2.2.4 on 2020-05-21 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0046_create_corporations_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='Junction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_test', models.CharField(choices=[('01', 'first-layer track height vs first-layer printing speed'), ('02', 'first-layer track width'), ('03', 'Extrusion temperature test'), ('04', 'extrusion temperature vs printing speed'), ('05', 'track width'), ('06', 'extrusion multiplier vs printing speed'), ('07', 'printing speed'), ('08', 'extrusion temperature vs retraction distance'), ('09', 'retraction distance vs printing speed'), ('10', 'retraction distance'), ('11', 'retraction distance vs retraction speed'), ('12', 'bridging extrusion multiplier vs bridging printing speed')], default='', max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='PrintDescriptor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statement', models.CharField(default="There's a problem with the print", max_length=512)),
                ('target_test', models.CharField(choices=[('01', 'first-layer track height vs first-layer printing speed'), ('02', 'first-layer track width'), ('03', 'Extrusion temperature test'), ('04', 'extrusion temperature vs printing speed'), ('05', 'track width'), ('06', 'extrusion multiplier vs printing speed'), ('07', 'printing speed'), ('08', 'extrusion temperature vs retraction distance'), ('09', 'retraction distance vs printing speed'), ('10', 'retraction distance'), ('11', 'retraction distance vs retraction speed'), ('12', 'bridging extrusion multiplier vs bridging printing speed')], default='', max_length=4)),
                ('hint', models.CharField(blank=True, max_length=512, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='descriptors')),
            ],
        ),
        migrations.CreateModel(
            name='SessionMode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Untitled', max_length=64)),
                ('type', models.CharField(choices=[('guided', 'Guided'), ('normal', 'Normal')], default='normal', max_length=64)),
                ('plan_availability', models.CharField(choices=[('basic', 'Core'), ('premium', 'Premium'), ('education', 'Education'), ('permanent', 'Permanent'), ('test', 'Test')], default='basic', max_length=64)),
                ('public', models.BooleanField(default=True)),
                ('_included_tests', models.CharField(default="['01', '02', '03', '04', '05', '06', '07', '08', '09', '10', '11', '12', '13']", max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='TestInfo',
        ),
        migrations.AlterField(
            model_name='session',
            name='_test_number',
            field=models.CharField(choices=[('01', 'first-layer track height vs first-layer printing speed'), ('02', 'first-layer track width'), ('03', 'Extrusion temperature test'), ('04', 'extrusion temperature vs printing speed'), ('05', 'track width'), ('06', 'extrusion multiplier vs printing speed'), ('07', 'printing speed'), ('08', 'extrusion temperature vs retraction distance'), ('09', 'retraction distance vs printing speed'), ('10', 'retraction distance'), ('11', 'retraction distance vs retraction speed'), ('12', 'bridging extrusion multiplier vs bridging printing speed')], default='01', max_length=20),
        ),
        migrations.AddField(
            model_name='junction',
            name='descriptors',
            field=models.ManyToManyField(blank=True, to='session.PrintDescriptor'),
        ),
        migrations.AddField(
            model_name='session',
            name='mode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='session.SessionMode'),
        ),
    ]
