# Generated by Django 2.2.4 on 2020-05-22 06:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0050_manual_assign_test_mode_to_all_existing_sessions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='mode',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='session.SessionMode'),
        ),
    ]
