# Generated by Django 2.2.4 on 2020-05-27 07:30

from django.db import migrations, models


def rename_testing_modes(app, schema_editor):
    db_alias = schema_editor.connection.alias

    SessionMode = app.get_model('session', 'SessionMode')

    advanced = SessionMode.objects.using(db_alias).get(name='Advanced')
    advanced._plan_availability = "['premium']"
    advanced.save()

    guided = SessionMode.objects.using(db_alias).get(name='Guided')
    guided._plan_availability = "['premium']"
    guided.save()

    core = SessionMode.objects.using(db_alias).get(name='Core')
    core._plan_availability = "['basic']"
    core.name = 'Guided (Free Tests Only)'
    core.save()

class Migration(migrations.Migration):

    dependencies = [
        ('session', '0053_auto_20200523_2356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessionmode',
            name='_plan_availability',
            field=models.CharField(default='["basic", "premium"]', max_length=64),
        ),
        migrations.RunPython(rename_testing_modes)
    ]
