# Generated by Django 2.2.4 on 2020-05-27 07:30

from django.db import migrations, models


def delete_all_modes(app, schema_editor):
    db_alias = schema_editor.connection.alias
    SessionMode = app.get_model('session', 'SessionMode')

    modes = SessionMode.objects.using(db_alias).all()
    for mode in modes:
        mode.delete()


def populate_testing_modes(app, schema_editor):
    db_alias = schema_editor.connection.alias

    SessionMode = app.get_model('session', 'SessionMode')

    SessionMode.objects.using(db_alias).create(name='Advanced',
                                               type='normal',
                                               _plan_availability="['premium']")

    SessionMode.objects.using(db_alias).create(name='Guided',
                                               type='guided',
                                               _plan_availability="['premium']")

    SessionMode.objects.using(db_alias).create(name='Guided (Free Tests Only)',
                                               type='guided',
                                               _included_tests="['01', '03', '10']",
                                               _plan_availability="['basic']")

class Migration(migrations.Migration):

    dependencies = [
        ('session', '0053_auto_20200523_2356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessionmode',
            name='_plan_availability',
            field=models.CharField(default='["basic", "premium"]', max_length=64),
        ),
        migrations.RunPython(delete_all_modes),
        migrations.RunPython(populate_testing_modes)
    ]
