# Generated by Django 2.2.4 on 2020-05-27 07:30

from django.db import migrations, models
from django.utils.translation import gettext_noop as _


def add_and_assign_descriptors(app, schema_editor):
    db_alias = schema_editor.connection.alias

    PrintDescriptor = app.get_model('session', 'PrintDescriptor')
    Junction = app.get_model('session', 'Junction')
    descriptors = [
            ([], _("Is the nozzle too close to the print bed?"), "00", None),
            (["08", "09"], _("All combinations are bad."), "09", _("Extruder's nozzle may be too large to retract filament successfully")),
            ([], _("All combinations are bad."), "09", None),
            (["10"], _("Are all values between 0 and 6 mm bad?"), "08", None),
            (["07"], _("Are there voids between tracks?"), "07", _("Try lowering printing speed values in the interval.")),
            (["03", "04", "05", "06"], _("I wish to fine-tune printing speed."), "07", None),
            (["05"], _("Are there still voids between tracks?"), "06", None),
            (["03"], _("I wish to fine-tune track height (print resolution)."), "04", None),
            (["03", "04"], _("Are there voids between tracks?"), "05", None),
            (["01"], _("Are there voids between tracks?"), "02", None),
            (["01"], _("Does the print peel off from print bed, although the height is correct?"), "01", _("Try increasing extrusion temperature, reduce printing speed, increase print bed temperature or apply an adhesive to the print bed.")),
            (["00", "01"], _("Does the print float above the print bed?"), "00", None),


    ]
    for descriptor in descriptors:
        desc = PrintDescriptor.objects.using(db_alias).create(statement=descriptor[1],
                                                              target_test=descriptor[2],
                                                              hint=descriptor[3])
        for test in descriptor[0]:
            junction = Junction.objects.using(db_alias).get(base_test=test)
            junction.descriptors.add(desc)
            junction.save()

# statement = model
# target_test = mod
# hint = models.Cha

class Migration(migrations.Migration):

    dependencies = [
        ('session', '0054_auto_20200527_1030'),
    ]

    operations = [
        migrations.RunPython(add_and_assign_descriptors)
    ]
