# Generated by Django 2.2.4 on 2020-05-27 07:30

from django.db import migrations, models


def add_and_assign_descriptors(app, schema_editor):
    db_alias = schema_editor.connection.alias

    PrintDescriptor = app.get_model('session', 'PrintDescriptor')
    Junction = app.get_model('session', 'Junction')
    descriptors = [
        (["01"], "Print floats above the print bed.", "01", "Check calibration, contact support"),
        (["01"], "Print does not stick to print bed.", "01", "Try increasing extrusion temperature, reduce printing speed, increase print bed temperature or apply an adhesive to the print bed."),
        (["01"], "There are voids between the printed tracks.", "02", None),
        (["03", "04"], "There are voids between the printed tracks.", "05", None),
        (["03"], "I wish to fine-tune track height (print resolution).", "04", None),
        (["05"], "There still are voids between the printed tracks.", "06", None),
        (["03", "04", "05", "06"], "I wish to fine-tune printing speed.", "07", None),
        (["07"], "Voids between tracks have appeared after printing this test.", "07", "Try lowering printing speed values in the interval."),
        (["10"], "No retraction distance values between 0 and 6 mm were successful.", "08", None),
        (["08"], "No combination of retraction distance and printing temperature was successful.", "09", None),
        (["09"], "No combination of retraction distance and printing speed was successful.", "13", "Extruder's nozzle may be too large to retract filament successfully"),
    ]
    for descriptor in descriptors:
        desc = PrintDescriptor.objects.using(db_alias).create(statement=descriptor[1],
                                                              target_test=descriptor[2],
                                                              hint=descriptor[3])
        for test in descriptor[0]:
            junction = Junction.objects.using(db_alias).get(base_test=test)
            junction.descriptors.add(desc)
            junction.save()

# statement = model
# target_test = mod
# hint = models.Cha

class Migration(migrations.Migration):

    dependencies = [
        ('session', '0054_auto_20200527_1030'),
    ]

    operations = [
        migrations.RunPython(add_and_assign_descriptors)
    ]
