# Generated by Django 2.2.4 on 2020-06-04 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0057_auto_20200603_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='form',
            field=models.CharField(choices=[('elliptic', 'Delta'), ('cartesian', 'Cartesian')], default='cartesian', max_length=20),
        ),
    ]
