# Generated by Django 2.2.4 on 2020-06-04 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0057_auto_20200603_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='corporation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='payments.Corporation'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='form',
            field=models.CharField(choices=[('elliptic', 'Delta'), ('cartesian', 'Cartesian')], default='cartesian', max_length=20),
        ),
        migrations.AlterField(
            model_name='material',
            name='corporation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='payments.Corporation'),
        ),
    ]
