# Generated by Django 2.2.4 on 2020-06-09 15:00

from django.db import migrations, models

SESSION_NUMBER_BASE = 100000

def init_session_numbers(app, schema_editor):
    db_alias = schema_editor.connection.alias
    Corporation = app.get_model('payments', 'Corporation')
    User = app.get_model('authentication', 'User')


    for corp in Corporation.objects.using(db_alias).all():
        i = 1
        for session in corp.session_set.order_by('pub_date'):
            session.number = SESSION_NUMBER_BASE + i
            session.save()
            i += 1

    for user in User.objects.using(db_alias).all():
        i = 1
        for session in user.session_set.filter(corporation=None).order_by('pub_date'):
            session.number = SESSION_NUMBER_BASE + i
            session.save()
            i += 1


def reset_session_numbers(app, schema_editor):
    db_alias = schema_editor.connection.alias
    Session = app.get_model('session', 'Session')


    Session.objects.using(db_alias).update(number=0)


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0059_auto_20200604_1718'),
    ]

    operations = [
            migrations.RunPython(init_session_numbers, reset_session_numbers)
    ]



