# Generated by Django 2.2.4 on 2020-06-11 06:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0060_init_session_numbers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='corporation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='payments.Corporation'),
        ),
    ]
