# Generated by Django 2.2.4 on 2020-06-11 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0061_auto_20200611_0939'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='gcode_download_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
