# Generated by Django 2.2.4 on 2020-06-11 13:20

from django.db import migrations, models

def adjust_session_numbers(app, schema_editor):
    db_alias = schema_editor.connection.alias
    Session = app.get_model('session', 'Session')

    Session.objects.using(db_alias).update(number=models.F('number') % 100000 + 1000)


def reset_session_numbers(app, schema_editor):
    db_alias = schema_editor.connection.alias
    Session = app.get_model('session', 'Session')

    Session.objects.using(db_alias).update(number=models.F('number') % 1000 + 100000)


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0062_session_gcode_download_count'),
    ]

    operations = [
            migrations.RunPython(adjust_session_numbers, reset_session_numbers)
    ]
