# Generated by Django 2.2.4 on 2020-07-30 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0068_settings_offset_z'),
    ]

    operations = [
        migrations.AlterField(
            model_name='junction',
            name='base_test',
            field=models.CharField(choices=[('00', 'z-offset'), ('01', 'first-layer track height vs first-layer printing speed'), ('02', 'first-layer track width'), ('03', 'Extrusion temperature vs printing speed'), ('04', 'track height vs printing speed'), ('05', 'track width'), ('06', 'extrusion multiplier vs printing speed'), ('07', 'printing speed'), ('08', 'extrusion temperature vs retraction distance'), ('09', 'retraction distance vs printing speed'), ('10', 'retraction distance'), ('11', 'retraction distance vs retraction speed'), ('12', 'bridging extrusion multiplier vs bridging printing speed')], default='', max_length=4),
        ),
        migrations.AlterField(
            model_name='printdescriptor',
            name='target_test',
            field=models.CharField(choices=[('00', 'z-offset'), ('01', 'first-layer track height vs first-layer printing speed'), ('02', 'first-layer track width'), ('03', 'Extrusion temperature vs printing speed'), ('04', 'track height vs printing speed'), ('05', 'track width'), ('06', 'extrusion multiplier vs printing speed'), ('07', 'printing speed'), ('08', 'extrusion temperature vs retraction distance'), ('09', 'retraction distance vs printing speed'), ('10', 'retraction distance'), ('11', 'retraction distance vs retraction speed'), ('12', 'bridging extrusion multiplier vs bridging printing speed')], default='', max_length=4),
        ),
        migrations.AlterField(
            model_name='session',
            name='_test_number',
            field=models.CharField(choices=[('00', 'z-offset'), ('01', 'first-layer track height vs first-layer printing speed'), ('02', 'first-layer track width'), ('03', 'Extrusion temperature vs printing speed'), ('04', 'track height vs printing speed'), ('05', 'track width'), ('06', 'extrusion multiplier vs printing speed'), ('07', 'printing speed'), ('08', 'extrusion temperature vs retraction distance'), ('09', 'retraction distance vs printing speed'), ('10', 'retraction distance'), ('11', 'retraction distance vs retraction speed'), ('12', 'bridging extrusion multiplier vs bridging printing speed')], default='01', max_length=20),
        ),
    ]
