# Generated by Django 2.2.4 on 2020-08-04 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0069_auto_20200730_1533'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='buildplate',
            field=models.CharField(default='', max_length=50),
        ),
    ]
