# Generated by Django 2.2.4 on 2020-11-04 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0071_printdescriptor_invalidates_current_results'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='support_contact_distance',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=4),
        ),
        migrations.AddField(
            model_name='settings',
            name='support_pattern_spacing',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
    ]
