# Generated by Django 2.2.4 on 2019-10-08 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_user_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='onboarding',
            field=models.BooleanField(default=True),
        ),
    ]
