# Generated by Django 2.2.4 on 2019-10-17 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_user_onboarding'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='_onboarding_sections',
            field=models.CharField(default='[0, 1, 2, 3, 4]', max_length=32),
        ),
    ]
