# Generated by Django 2.2.4 on 2019-10-22 07:09

from django.db import migrations, models


def func_reset_default(apps, schema_editor):
    User = apps.get_model("authentication", "User")
    db_alias = schema_editor.connection.alias
    User.objects.using(db_alias).all().update(_onboarding_sections="['dashboard', 'new_session', 'session_generate_1', 'session_validate', 'session_generate_2']")


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_user__onboarding_sections'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='_onboarding_sections',
            field=models.CharField(default="['dashboard', 'new_session', 'session_generate_1', 'session_validate', 'session_generate_2']", max_length=256),
        ),
        migrations.RunPython(func_reset_default)
    ]
