# Generated by Django 2.2.4 on 2019-11-06 12:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_manual_set_all_users_to_expire_after_formnext'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_active',
            field=models.DateTimeField(null=True),
        ),
    ]
