# Generated by Django 2.2.4 on 2020-01-29 14:00

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0016_manual_set_all_users_to_expire_after_31st_march_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='subscription_expiration',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 31, 0, 0, tzinfo=utc)),
        ),
    ]
