# Generated by Django 2.2.4 on 2020-03-26 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0017_auto_20200129_1600'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='can_access_investor_dashboard',
            field=models.BooleanField(default=False),
        ),
    ]
