# Generated by Django 2.2.4 on 2020-03-30 18:10

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0019_manual_set_all_users_to_expire_after_30th_april_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='plan',
            field=models.CharField(choices=[('basic', 'Core'), ('premium', 'Premium'), ('education', 'Education'), ('permanent', 'Permanent'), ('test', 'Test')], default='basic', max_length=32),
        ),
        migrations.AlterField(
            model_name='user',
            name='subscription_expiration',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 30, 0, 0, tzinfo=utc)),
        ),
    ]
