# Generated by Django 2.2.4 on 2020-04-22 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0022_add_company_account_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='company_legal_address',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
