# Generated by Django 2.2.4 on 2020-06-15 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0025_create_corporations_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='_plan',
            field=models.CharField(choices=[('basic', 'Core'), ('premium', 'Premium'), ('education', 'Education'), ('permanent', 'Permanent'), ('test', 'Test'), ('limited', 'Limited')], db_column='plan', default='basic', max_length=32),
        ),
    ]
