# Generated by Django 2.2.4 on 2021-06-20 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0028_auto_20201025_1237'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='custom_payments',
            field=models.BooleanField(default=False, help_text='Mark true to hide subscriptions page from user'),
        ),
    ]
