TEST_NUMBER_CHOICES = [("01", "First-layer printing height test"), ("03", "Extrusion temperature test")]
SLICER_CHOICES = [("Prusa", "Slic3r PE"), ("Simplify3D", "Simplify3D"), ("Cura", "Cura")]
TARGET_CHOICES = [("MS", "Mechanical Strength"), ("A", "Aesthetics"), ("FP", "Fast Printing")]
TOOL_CHOICES = [("T0", "T0"), ("T1", "T1"), ("T2", "T2")]
FORM_CHOICES = [("elliptic", "Elliptic"), ("cartesian", "Cartesian")]
